spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: plspejrcgdp29h669nkj6p96m
            scope: openid, email, phone
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: cognito
        provider:
          cognito:
            authorization-uri: https://web01.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://web01.auth.us-east-1.amazoncognito.com/oauth2/token
            user-info-uri: https://web01.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            user-name-attribute: sub
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eyYU7A9vh/.well-known/jwks.json
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_eyYU7A9vh
